FROM node:24.13.0-bookworm AS image
WORKDIR /app
COPY ./package.json .

FROM image AS build
ARG env=DEV
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

EXPOSE 3004

CMD ["npm", "run", "start"]
