version: '3.9'
services:
  byk-widget:
    container_name: byk-customer-support
    image: harbor.riaint.ee/byk/customer-service:243
    ports:
      - 3001:443
    volumes:
      - ./nginx/http-nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - bykstack

networks:
  bykstack:
    name: ruuter_bykstack
